### ISSUE TITLE
keyboard repeat in vterm not working

### ISSUE THREAD

**Issue by slartibart70** [htrefil/rkvm#56] opened 2023-11-30 18:55 UTC
If i connect to a remote linux instance (fedora38, wayland) to a GUI, the keyboard connected to the server sends 'auto-repeat' characters if i press a key long enough (as totally expected).
But, if i switch to a vterm on the target (Ctrl-Alt-3, 4, ...) in text-only mode, the keyboard does not send repeats. Single key events are transported properly.

Any idea how to fix this?

**Comment by htrefil** [comment] 2023-12-02 12:23
I was able to reproduce the bug on my X11 machine too.

I believe it may be due to rkvm not sending EV_REP events.

**Comment by htrefil** [comment] 2023-12-02 13:56
Fixed in 0.6.0.

**Closed as completed by htrefil** 2023-12-02 13:56 UTC
